### ISSUE TITLE
你这没有领域对象 作用是什么

### ISSUE THREAD

**Issue by weifengliuhen** [AmosWang0626/think-cola#11]
你这没有领域对象 作用是什么,没看到和3层架构有啥区别

**Comment by AmosWang0626** [comment]
> 你这没有领域对象 作用是什么,没看到和3层架构有啥区别

示例的项目比较简单，没有引入很多DDD的内容，所以领域层比较单薄，没有复杂的领域对象。

和传统三层架构的区别：
1. 传统三层，Controller Service Dao，多层间耦合比较重。在复杂的项目中，没法很好地分治，尤其 Service 很容易膨胀。
2. COLA 中引入了 App层，也通过 Command 做了读写分离，会使得 App层功能更清晰，避免了 Service 内容过多膨胀严重。
3. Infrastructure层一般很有用，防腐层，会去隔离DB、RPC等外部依赖，App层使用时，就不用关心外部依赖的问题了，可以更专注地实现业务。

本质上还是分治思想，层次丰富了，职责单一、条理会更清晰。

当然在简单项目下，三层架构很清晰明了，也不失为一个好选择。
