### ISSUE TITLE
有两个问题探讨一下

### ISSUE THREAD

**Issue by lslvxy** [AmosWang0626/think-cola#2]
最近也在熟悉COLA架构 ,准备撸一个轮子
目前遇到几个问题可以一起探讨下么
1. 按照COLA的架构 domain 层是不依赖client层的 ,我看cola的实例代码和你的代码都是有依赖的.而且如果不依赖client的话那么gateway中无法使用qry参数那必须再封装一个qry对象么?
2. 关于Qry参数封装比如我有一个UserQuery extends Query 和一个UserPageQry extends PageQuery ,这样UserQuery和UserPageQry 代码基本重复了有好的办法么?
3. 关于你说的Entity对象如果不需要BaseDO中的属性那么如果需要查询创建人创建时间怎么搞
4. 按照架构上说domain Object是可选的,而domain层不依赖其他模块,那么Gateway中应该返回什么POJO呢

求赐教

**Comment by AmosWang0626** [comment]
1. domain依赖client，这个按实际情况来吧。即便domain里边用不到，infrastructure里也有可能用到，所以domain依赖client是可行的。另外，如果不依赖client，query可以不走domain gateway，直接走infrastructure里的mapper或者repository
2. UserQuery和UserPageQry代码重复的，少量字段重复其实不用太在意。也可以在UserPageQry加一个 private UserQuery userQuery;
3. Entity和DO，创建人那些说的有点绝对，描述我改了下。根据最近的学习，实体和DO是有区别的，实体里边可以封装一些操作，但DO一般只是与数据库相对应的，做持久化用的
4. domain的gateway应该返回Entity这些吧，就是纯domain里边的POJO

问题问得很好，上边是我的一些想法，可能不对，咱可以继续探讨哈
