### ISSUE TITLE
打包部署的问题

### ISSUE THREAD

**Issue by 20130101** [AmosWang0626/think-cola#4]
请问按cola分层后，应用think-cola部署怎么能整体打成一个jar包

**Comment by AmosWang0626** [comment]
start模块处于模块依赖的顶端，项目整体package之后，start对应的jar是一个完整的包

**Comment by 20130101** [comment]
感谢，提完issue后自己反应过来了，最近在学cola，打算用起来，要做一些分布式事务、消息队列、缓存等组件的集成验证
