### ISSUE TITLE
为什么我感觉业务逻辑都在application层了

### ISSUE THREAD

**Issue by springcloud-boot** [AmosWang0626/think-cola#5]
domain层, 只定义了接口. 
实际上是infrastructure 实现. 

代码而言,application实现了部分逻辑,参数校验等, 是否存在.

infrastructure  实现了数据库的查询.  领域层做了什么?只是感觉放了一些domain,

**Comment by AmosWang0626** [comment]
因项目而异吧，简单的项目领域层做的确实不多；复杂点的项目，领域层是核心，不只是gateway接口，这就是DDD的范畴了，可以参考下COLA那个示例项目：[https://github.com/alibaba/COLA/tree/master/samples/craftsman/craftsman-domain/src/main/java/com/alibaba/craftsman/domain](https://github.com/alibaba/COLA/tree/master/samples/craftsman/craftsman-domain/src/main/java/com/alibaba/craftsman/domain)

**Comment by uestcGJ** [comment]
> 因项目而异吧，简单的项目领域层做的确实不多；复杂点的项目，领域层是核心，不只是gateway接口，这就是DDD的范畴了，可以参考下COLA那个示例项目：https://github.com/alibaba/COLA/tree/master/samples/craftsman/craftsman-domain/src/main/java/com/alibaba/craftsman/domain

demo项目也很拉垮，太混乱了
