### ISSUE TITLE
问题探讨一下哈

### ISSUE THREAD

**Issue by rongflag** [AmosWang0626/think-cola#6]
1.COLA 4.0 我在刚刚的一个单体项目中已经使用了，虽然用的也不是很好，但能感觉到他的优势。但是在微服务中落地，我没有很好的思路，如果直接照搬，就会导致项目内的module过多，其实还更不好维护，你在这方面有过考虑吗？

**Comment by AmosWang0626** [comment]
个人观点哈。这个主要还看项目规模，从我接触的项目来看，一个项目4～7个模块很正常，只要模块的功能相近，上手一个项目后，其他项目也很好上手的。
分模块的主要作用还是隔离，分包不能解决很多类访问的问题，分了模块就能从根本上隔离开了。
